language: python
python:
- 2.7
evv:
- DOCKER_CONTENT_TRUST=0
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- docker-compose -f docker-compose-build.yml build
- docker-compose -f docker-compose-build.yml up -d
- docker-compose -f docker-compose-build.yml ps
before_script:
- pip install requests
- pip install docker
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/symfony4-restful:app
env:
  global:
  - secure: U+fOCrzBnH/AsikWglupVfs6nr8Up7OwN7qETeOe9vlyDwImIWIaJ6K+PhHN5wohLvl1h1GDHNjO8ZxH0exPAOSf0XofkLNSXld6cPWlhwpZte4p4+9ifsOKV9Bq3B9azkPo+H+S1328DRgiBZB8RyH7PeHgmeZSKs3yQuiRd/MwCrHM6Ah/a3Nrtu08tLIeOjKvM6FPj7mzAyx7L3p+167Oncq5LzxtPeqm5L1u7IqbcHR7kJ49icN/YYIeXtunUl+ESVPNT9A6YHVWJAt4tIq9FTjmCMmV/nhQypwTwbuFFOP0H4iUopVUJ8hfKvdHwHAqhqFsSmK1bEi5Ts+NqokJgS1xCzVQ8MaaTwPjjVJMXHGI5E12Sk8z2qintXoHr9hJlj1BoXL/4bvZ+vqDYkEzQXkbLKgIZaDmo0+6bzGwEfviuM44PXKO0sVsm39s00Cr1WqiugIee3oxG53cCkvikndES3ubJY9esvOTLI5ZgJxRpM02oZwJWR7AJNZTkHJW6OwRiRUhL0u4sO33ESg32Do9JeNnRvXy0+18a55X/eOg/2ZJlE4jSn2bO1y3JL46m36kop7dwd+gUbsxSc3+Sxx/ncMiefqRzqq54k3RgceBSXGjZQdZE3erK3TkjVXQnuCs8zDBwZiYrdU+lnEQdN6WGDPGxbxkG95TxGI=
  - secure: FnNECxyhcFY3KHb6gUH3pgpv+A91Jj2JCTJvCW3FCSIkOVrqqWY6a2+AyCd/5se2QOY49okYRnOsfSTFXQ/f3/sFu/IIxK0X+mXhI4u7PbMeII/AQT2M9un+Ict+1QWUX+csDkgc9HB5ALu8/aAOB1YenN8VAX1t/zhYgdYNZwhCcRRhdaqZGytim6oZo83svz30CY+BXrxFig0/kDDJZ+HkrQA3EueTVKycMM5StPrbsYfVwC8VG/qa5zT+86y9o2RK7kylzriZHm7YyZXjhK8/4igIcpoxytcGqGm8SSswSXZsoq4Zo7sLc4ldVcbzv8LtBT0fYN1n61Q64kq7Auqj1TZ0YXo6M6vNVXmJ5vLgsYA4zVfeyuDgIYXvBVP7KDuCuSUjkRp1YFPJcIZOh77gUylrVCfbR4S3eoC39kFYPmdRClPSrJnsuoXaQNEj6fslTdyMF2YEA/hArE7uja658oP0nEgIE7d+ZEPPxbj6cGshjtY7JSHR64czuGxUXh3OOMTzrFk1RmwCpCx8+bt2YVgrpvKCNqweFvx8/L0pEBumjyNJY23XXel008avT5uqV7uYuEuBVFFEWshoPkE96UJKBkueeTIyeuJrsuURpEjvt3pBQZJ8vRVfyrkpReWgVWFpIqdLBLy00Gzy1cps8GvlAFQD9rQBDJIBt5A=
