version: "2"

volumes:
    db:
      driver: local

services:

  php:
    build: ./dockerfiles/php
    restart: always
    container_name: php
    env_file:
         - .env
    user: 1001:1001
    links:
      - db
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=0.0.0.0
    volumes:
      - ./symfony:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./xdebug.ini:/usr/local/lib/php/doc/xdebug/xdebug.ini
    logging:
         driver: "json-file"
         options:
           max-size: "10m"
           tag: "container_{{.Name}}"


  elasticsearch:
    image: elasticsearch:5.4.3
    restart: always
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./elasticsearch-data/data:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  kibana:
      image: kibana:5.4.3
      restart: always
      container_name: kibana
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"
      links:
        - elasticsearch
      volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
      build: config/logstash/
      environment:
        LS_JAVA_OPTS: "-Xms1g -Xmx4g"
      container_name: logstash
      restart: always
      ports:
        - "5044:5044"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

  redis:
      image: redis:latest
      restart: always
      container_name: redis
      env_file:
        - .env
      volumes:
        - ./redis-data:/data
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          tag: "container_{{.Name}}"


  db:
    image: mysql:5.7
    restart: always
    container_name: mysql57-container
    ports:
      - "127.0.0.1:3357:3306"
    env_file: .env
    environment:
      DB_CONNECTION: mysql
    volumes:
      - db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        tag: "container_{{.Name}}"


# entry point
  nginx:
    image: ${REGISTRY}trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - kibana
    volumes:
      - ./certs/ssl:/etc/nginx/ssl
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./supervisord:/etc/supervisor/conf.d/
      - ./cron/nginx:/var/spool/cron/crontabs
      - ./symfony:/var/www/html
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        tag: "container_{{.Name}}"
